# Generated by Django 6.0.3 on 2026-04-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('Power', 'Power Outage'), ('Water', 'Water Leak'), ('Pothole', 'Pothole')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('reporter_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Logged', 'Logged'), ('In Progress', 'Technician Dispatched'), ('Resolved', 'Resolved')], default='Logged', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
