# Generated by Django 6.0.3 on 2026-04-14 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fault',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fault',
            name='status',
        ),
        migrations.AlterField(
            model_name='fault',
            name='contact_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='fault',
            name='nature',
            field=models.CharField(choices=[('Water', 'Water'), ('Power', 'Power'), ('Roads', 'Roads'), ('Sewerage', 'Sewerage')], max_length=20),
        ),
    ]
