# Generated by Django 6.0.3 on 2026-04-14 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_fault_created_at_remove_fault_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fault',
            name='ref_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fault',
            name='status',
            field=models.CharField(default='Logged', max_length=20),
        ),
    ]
